apiVersion: v1
kind: Pod
metadata:
  name: gl-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: pyopengl-test
    image: pyopengl:1.0
    imagePullPolicy: IfNotPresent
    command: ['bash', 'start.sh']
    volumeMounts:
      - name: app
        mountPath: /home
  volumes:
    - name: app
      hostPath:
        path: /media/wxy/ubuntu/workspace/app
